[build]
builder = "nixpacks"

[deploy]
startCommand = "python simple_main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production]
PORT = 8001