global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-specific-password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email'
  routes:
    - match:
        severity: 'critical'
      receiver: 'email-and-sms'

receivers:
  - name: 'email'
    email_configs:
      - to: 'your-team@your-company.com'
        send_resolved: true
        headers:
          subject: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}'
  
  - name: 'email-and-sms'
    email_configs:
      - to: 'oncall@your-company.com'
        send_resolved: true
    webhook_configs:
      - url: 'http://sms-gateway/send'
        send_resolved: true

templates:
- '/etc/alertmanager/templates/*.tmpl'
