version: '3.8'

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: elmowafy-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/elmowafy-travels
      - JWT_SECRET=your_jwt_secret_key_here
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - elmowafy-network

  mongodb:
    image: mongo:6.0
    container_name: elmowafy-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=elmowafy-travels
    restart: unless-stopped
    networks:
      - elmowafy-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: elmowafy-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=example
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - elmowafy-network

networks:
  elmowafy-network:
    driver: bridge

volumes:
  mongodb_data:
