[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.family"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
[environments.production.variables]
FLASK_ENV = "production"
PORT = 8000
VLLM_API_URL = "http://localhost:8000"